# Generated by Django 3.0.8 on 2020-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200727_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='event_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='event id'),
        ),
    ]
