# Generated by Django 3.0.7 on 2020-07-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200728_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='vbb email'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='vbb_email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='vbb email'),
        ),
    ]
