# Generated by Django 3.0.7 on 2020-07-30 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200728_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hsm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(167)], verbose_name='hours since monday at 12am (eastern time)'),
        ),
    ]
