# Generated by Django 3.0.7 on 2020-08-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200803_1756'),
        ('api', '0008_auto_20200731_1738'),
    ]

    operations = [
    ]
