# Generated by Django 3.0.7 on 2020-08-06 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_merge_20200804_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='library',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='calendar id'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
