# Generated by Django 3.0.8 on 2020-08-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200805_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='room_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='room id'),
        ),
        migrations.AddField(
            model_name='library',
            name='calendar_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='library classroom'),
        ),
        migrations.AddField(
            model_name='library',
            name='library_classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='library classroom'),
        ),
        migrations.AddField(
            model_name='library',
            name='library_gmail_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='library gmail group'),
        ),
        migrations.AddField(
            model_name='library',
            name='program_director_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='program director email'),
        ),
        migrations.AddField(
            model_name='library',
            name='program_director_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='program director name'),
        ),
        migrations.AddField(
            model_name='library',
            name='program_director_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='program director phone'),
        ),
        migrations.AddField(
            model_name='library',
            name='whatsapp_group',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='whatsapp group'),
        ),
    ]
