# Generated by Django 3.0.7 on 2020-08-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200809_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='calendar id'),
        ),
    ]
