# Generated by Django 3.0.8 on 2020-08-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200810_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='contact_source',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='referral_source',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='referral source'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='room id'),
        ),
        migrations.AlterField(
            model_name='library',
            name='calendar_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='library calendar'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='involvement',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='additional involvement'),
        ),
    ]
