# Generated by Django 3.0.8 on 2020-08-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200812_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='affiliation'),
        ),
    ]
