# Generated by Django 3.0.8 on 2020-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200812_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='initials',
            field=models.TextField(max_length=6, null=True),
        ),
    ]
