# Generated by Django 3.0.8 on 2020-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200812_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='personal_email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='vbb_email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
    ]
