# Generated by Django 3.0.8 on 2020-08-12 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200812_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hsm',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(167.999)], verbose_name='hours since monday at 12am (eastern time)'),
        ),
    ]
