# Generated by Django 3.0.8 on 2020-08-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200812_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computer',
            new_name='MenteeComputer',
        ),
    ]
