# Generated by Django 3.0.8 on 2020-08-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_auto_20200812_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp', to=settings.AUTH_USER_MODEL),
        ),
    ]
