# Generated by Django 3.0.8 on 2020-08-12 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200812_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionslot',
            name='msm',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10079)]),
        ),
    ]
