# Generated by Django 3.0.8 on 2020-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200812_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
