# Generated by Django 3.0.8 on 2020-08-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200818_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='adult',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='charged',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='vbb_chapter',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='advisor_notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='desired_involvement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='referral_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
